Bring in patch for display label
ubports/qtpim-opensource-src-packaging pull request #4
Opened 2019-05-29 19:29 UTC by mardy

This will almost certainly be merged upstream soon.

2019-06-14 00:43 UTC, UniversalSuperBox approved these changes

2019-06-14 00:45 UTC, UniversalSuperBox requested changes
Wait... For the test failure, `xvfb-run` needs to be run with the arguments `--server-args "-screen 0 1024x768x24"`. If we can do that, then tests should start.

2019-06-15 07:24 UTC, mardy commented
> Wait... For the test failure, `xvfb-run` needs to be run with the arguments `--server-args "-screen 0 1024x768x24"`. If we can do that, then tests should start.

Thanks! That, plus another environment variable, did the trick! Please review it again :-)

2019-06-15 13:06 UTC, UniversalSuperBox approved these changes

2019-06-15 13:06 UTC, merged